// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC96_ErQ5ilYAZ_sF97BlItlicePnzmVNI',
    appId: '1:711421784258:web:fa09ee4a2ddd4efb914b5b',
    messagingSenderId: '711421784258',
    projectId: 'ruya-perisi-288a7',
    authDomain: 'ruya-perisi-288a7.firebaseapp.com',
    storageBucket: 'ruya-perisi-288a7.appspot.com',
    measurementId: 'G-3KC0H5TE6S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWZ0coBTLfpPUF3-0zGWAhzc6w6IBYKYg',
    appId: '1:711421784258:android:3ec77bc46a44db5a914b5b',
    messagingSenderId: '711421784258',
    projectId: 'ruya-perisi-288a7',
    storageBucket: 'ruya-perisi-288a7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVIc8xMZrEyhlF2iwOQYB-BU_bohdBgfU',
    appId: '1:711421784258:ios:8acba51e6c133a94914b5b',
    messagingSenderId: '711421784258',
    projectId: 'ruya-perisi-288a7',
    storageBucket: 'ruya-perisi-288a7.appspot.com',
    androidClientId: '711421784258-8mt1vko0snrqj0ijaigar1pgmfdl73h7.apps.googleusercontent.com',
    iosClientId: '711421784258-vhsdvbv2lad9d3muu40idisk7dbqv0nm.apps.googleusercontent.com',
    iosBundleId: 'com.bonjour.ruyaperisi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDVIc8xMZrEyhlF2iwOQYB-BU_bohdBgfU',
    appId: '1:711421784258:ios:3afc7ae5e1c74eb7914b5b',
    messagingSenderId: '711421784258',
    projectId: 'ruya-perisi-288a7',
    storageBucket: 'ruya-perisi-288a7.appspot.com',
    androidClientId: '711421784258-8mt1vko0snrqj0ijaigar1pgmfdl73h7.apps.googleusercontent.com',
    iosClientId: '711421784258-hanu5ai2294jn78eup3k6e3lamh20g77.apps.googleusercontent.com',
    iosBundleId: 'com.example.dream',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyACyJy0E4iGx1QWI-8gJHvyGQC36WyhX2U',
    appId: '1:711421784258:web:9c312012e723bf3d914b5b',
    messagingSenderId: '711421784258',
    projectId: 'ruya-perisi-288a7',
    authDomain: 'ruya-perisi-288a7.firebaseapp.com',
    storageBucket: 'ruya-perisi-288a7.appspot.com',
    measurementId: 'G-R0WR31BDFV',
  );
}
